# -*- coding: utf-8 -*-
"""Translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVM_imY4ZAb8VzUd9ZgaPya2PB7hvYcV
"""

from transformers import AutoModelForCausalLM, AutoTokenizer
# !pip install googletrans==4.0.0-rc1
from googletrans import Translator

# Load a pre-trained conversational model (mBART is multilingual)
model_name = "facebook/mbart-large-50"
model = AutoModelForCausalLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
translator = Translator()

# Function to generate responses
def generate_response(user_input, target_language):
    # Translate input to English for the model
    translated_input = translator.translate(user_input, dest='en').text

    # Tokenize input
    inputs = tokenizer.encode(translated_input, return_tensors="pt")

    # Generate response
    outputs = model.generate(inputs, max_length=150, num_beams=5, early_stopping=True)
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Translate the model's response back to the target language
    translated_response = translator.translate(response, dest=target_language).text
    return translated_response

# Main conversation loop
def chat():
    print("Welcome to the multi-lingual translator bot! (Type 'quit' to exit)")
    languages = {
    'English': 'en',
    'Spanish': 'es',
    'French': 'fr',
    'German': 'de',
    'Chinese': 'zh-cn',
    'Hindi': 'hi',
    'Arabic': 'ar'
    }
    print('Available languages:')
    for lang, code in languages.items():
        print(f'{code} : {lang}')
    language = input("Select your language: ").lower()

    while True:
        user_input = input("You: ")

        if user_input.lower() == 'quit':
            print("Goodbye!")
            break

        # Generate bot response based on user input and preferred language
        bot_response = generate_response(user_input, language)
        print(f"Bot: {bot_response}")

# Start the conversation
if __name__ == '__main__':
    chat()

